name: PlayerStatus
version: 1.1.0
author: TheBeefSteak
main: net.angusbeefgaming.playerstatus.PS
commands:
  player:
    description: Look up player information
api-version: 1.13
authors: [TheBeefSteak, kbulgrien]
website: https://www.spigotmc.org/resources/player-status.44041/
usage: "Usage: /player <username> - Open the GUI for a player"
permissions:
  playerstatus.open:
    description: Open the GUI
    default: op
